# Generated by Django 4.1.2 on 2022-12-21 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'جساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to='account/profile', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='melicode',
            field=models.CharField(max_length=11, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
