# Generated by Django 4.1.2 on 2022-11-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
