# Generated by Django 4.1.2 on 2022-12-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ticket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
