# Generated by Django 4.1.2 on 2022-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
