# Generated by Django 4.1.2 on 2022-12-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['updated'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
