# Generated by Django 4.1.2 on 2022-12-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_like_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
